#!/bin/bash


PROG=/usr/bin/python
MATRIX_CONFIG=/data/photoframe/conf/matrix_config.yml

test -x ${PROG} || exit 0

test -n "${OS_VERSION}" || source /etc/init.d/base


start() {
  msg_begin "Starting matrix client"
  /bin/mkdir -p /data/photoframe/log
  /bin/mkdir -p /data/photoframe/images_local
  ${PROG} -m matrix_photos -c ${MATRIX_CONFIG} &
  
  test $? == 0 && msg_done || msg_fail
}

stop() {
  msg_begin "Stopping matrix client"
  ps -A | grep -e "\s/usr/bin/python -m matrix_photos"  | awk 'FNR == 1 {print $1}' |  xargs kill -9 $1
  test $? == 0 && msg_done || msg_fail
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
esac

